version: '3'
services:
  web:
    build:
      context: .
      dockerfile: './web/Dockerfile'
    container_name: events
    expose:
     - "8000"
    command: ["./docker_run.sh"]
    env_file:
     - .env
    volumes:
     - ${USERDIR}/web/static/events:/static
     - ${USERDIR}/web/media/events:/media
    depends_on:
     - db

  db:
    build:
      context: .
      dockerfile: './db/Dockerfile'
    container_name: events_db
    ports:
     - "5444:5432"
    env_file:
     - .env
    volumes:
     - ${USERDIR}/web/postgres/events/data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: events_nginx
    ports:
      - "8001:8000"
    volumes:
     - ./src:/src
     - ${USERDIR}/web/static/events:/static
     - ${USERDIR}/web/media/events:/media
     - ./config/nginx:/etc/nginx/conf.d
    depends_on:
     - web
