# Generated by Django 2.2.3 on 2019-07-21 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_contact_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events_app.Contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
