# Generated by Django 2.2.3 on 2019-07-21 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_auto_20190721_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events_app.Contact'),
        ),
    ]
