# Generated by Django 2.2.3 on 2019-07-26 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0006_errorlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='event',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='event_location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='events_app.EventLocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorlog',
            name='event_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
